# Copyright (c) 2022-2026, The Isaac Lab Project Developers.
# SPDX-License-Identifier: BSD-3-Clause

"""
Script to play back a trained Diffusion Policy in the Isaac Lab simulator (closed-loop control).
Supports Receding Horizon Control (RHC) and executing transitions between walk and crouch
by following a 3D path loaded from a file or generated by default.

Example usage:
python scripts/diffusion_policy/play_policy.py --task="solo12-v0" \
    --checkpoint scripts/diffusion_policy/runs/walk_crouch_diffusion/best.pt \
    --path_file scripts/diffusion_policy/paths/my_s_curve.npy
"""

import argparse
import os
import sys
import time
import torch
import numpy as np
from pathlib import Path
from typing import Any, Dict, Tuple

# Setup paths
_PROJECT_ROOT = Path(__file__).resolve().parents[3]
_UPSTREAM_RSL_SCRIPT_DIR = _PROJECT_ROOT / "scripts" / "reinforcement_learning" / "rsl_rl"
if str(_UPSTREAM_RSL_SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(_UPSTREAM_RSL_SCRIPT_DIR))

# Launch omniverse app with GUI enabled
from isaaclab.app import AppLauncher

parser = argparse.ArgumentParser(description="Run closed-loop path following evaluation of a trained Diffusion Policy.")
parser.add_argument("--task", type=str, default="solo12-v0", help="Task name (e.g. solo12-v0).")
parser.add_argument("--checkpoint", type=str, required=True, help="Path to the saved checkpoint (.pt file).")
parser.add_argument("--guidance_scale", type=float, default=1.2, help="Classifier-free guidance scale.")
parser.add_argument("--num_envs", type=int, default=1, help="Number of environments to spawn.")
parser.add_argument("--num_inference_steps", type=int, default=15, help="Number of denoising steps during inference (default: 15 for fast RHC). Use 100 for exact DDPM.")
parser.add_argument("--path_file", type=str, default=None, help="Path to a .npy file containing [N, 3] or [N, 4] coordinates of the 3D path.")

parser.add_argument("--time_budget", type=float, default=3.0, help="Total time budget in seconds to reach the end of the path.")
parser.add_argument("--desired_speed", type=float, default=0.4, help="Fallback target speed if time budget is not used.")

# Add standard app launcher CLI arguments (GUI is enabled by default)
AppLauncher.add_app_launcher_args(parser)
args_cli, hydra_args = parser.parse_known_args()

# Strip parsed arguments from sys.argv so Hydra doesn't crash on them
sys.argv = [sys.argv[0]] + hydra_args

# Force headless = False to show the GUI window
args_cli.headless = False if args_cli.headless is None else args_cli.headless
app_launcher = AppLauncher(args_cli)
simulation_app = app_launcher.app

# Import libraries requiring active sim
import gymnasium as gym
from isaaclab_rl.rsl_rl import RslRlVecEnvWrapper
from isaaclab_tasks.utils.hydra import hydra_task_config

# Import model and geometry files
sys.path.insert(0, str(Path(__file__).resolve().parent))
from model.solo12_diffusion_policy import Solo12DiffusionPolicy, Solo12DiffusionPolicyConfig
from train.checkpoint_utils import load_training_checkpoint
from train.geometry import transform_point_to_local, transform_point_to_yaw_frame, relative_yaw, cumulative_xy_lengths



def get_proprioception_obs(raw_env: Any, joint_ids: slice, last_action: torch.Tensor) -> torch.Tensor:
    """Concatenates raw simulator states to form the 42-dimensional observation vector:
    [joint_pos (12), joint_vel (12), base_ang_vel (3), projected_gravity (3), last_action (12)]
    """
    robot = raw_env._robot
    joint_pos = robot.data.joint_pos[:, joint_ids]          # (num_envs, 12)
    joint_vel = robot.data.joint_vel[:, joint_ids]          # (num_envs, 12)
    base_ang_vel = robot.data.root_ang_vel_b                # (num_envs, 3)
    projected_gravity = robot.data.projected_gravity_b      # (num_envs, 3)
    
    obs = torch.cat([joint_pos, joint_vel, base_ang_vel, projected_gravity, last_action], dim=-1)
    return obs


def compute_path_following_goal(
    raw_env: Any,
    path_w: np.ndarray,
    yaws_w: np.ndarray,
    cumulative_lengths: np.ndarray,
    time_remaining_s: float,
    desired_speed: float,
    device: torch.device
) -> torch.Tensor:
    """Computes the 11-dimensional goal vector by projecting the path relative to the current robot state:
    - 3 local waypoints along the path (0.4m, 0.8m, 1.2m) = 6 dims
    - local target position at the end of the path (dx, dy, dz) = 3 dims
    - relative target yaw (dyaw) = 1 dim
    - required mean velocity v_req = clip(L_remaining / time_remaining, 0.0, 2.0) = 1 dim
    """
    robot = raw_env._robot
    pos_w = robot.data.root_pos_w.cpu().numpy()
    quat_w = robot.data.root_quat_w.cpu().numpy()
    num_envs = pos_w.shape[0]
    
    goals = []
    for i in range(num_envs):
        robot_pos = pos_w[i]
        robot_quat = quat_w[i]
        
        # 1. Find closest point on the path
        dists = np.linalg.norm(path_w[:, :2] - robot_pos[:2], axis=-1)
        start_idx = int(np.argmin(dists))
        start_s = cumulative_lengths[start_idx]
        
        # Target position is the final point of the path
        end_idx = len(path_w) - 1
        target_pos_w = path_w[end_idx]
        target_yaw_w = yaws_w[end_idx]
        
        # 2. Compute local waypoints at distances 0.4m, 0.8m, 1.2m along the path
        waypoints = []
        for dist in [0.4, 0.8, 1.2]:
            target_wp_s = start_s + dist
            wp_idx = int(np.searchsorted(cumulative_lengths, target_wp_s))
            wp_idx = min(wp_idx, end_idx)
            wp_local = transform_point_to_yaw_frame(path_w[wp_idx], robot_pos, robot_quat)
            waypoints.extend([float(wp_local[0]), float(wp_local[1])])
            
        # 3. Compute target relative position (dx, dy, dz)
        target_rel = transform_point_to_yaw_frame(target_pos_w, robot_pos, robot_quat)

        
        # 4. Compute relative yaw (dyaw)
        target_quat_wxyz = np.array([np.cos(target_yaw_w / 2.0), 0.0, 0.0, np.sin(target_yaw_w / 2.0)], dtype=np.float32)
        dyaw = relative_yaw(robot_quat, target_quat_wxyz)
        
        # 5. Compute required velocity along remaining path length
        path_length_remaining = float(cumulative_lengths[end_idx] - cumulative_lengths[start_idx])
        if time_remaining_s > 0.0:
            v_req = float(np.clip(path_length_remaining / (time_remaining_s + 1e-3), 0.0, 2.0))
        else:
            v_req = min(desired_speed, path_length_remaining / 1.0)
            
        goal_vec = np.asarray(
            [
                *waypoints,
                float(target_rel[0]),
                float(target_rel[1]),
                float(target_rel[2]),
                float(dyaw),
                float(v_req)
            ],
            dtype=np.float32
        )
        goals.append(goal_vec)
        
    return torch.from_numpy(np.stack(goals, axis=0)).to(device)


@hydra_task_config(args_cli.task, "rsl_rl_cfg_entry_point")
def main(env_cfg: Any, agent_cfg: Any):
    checkpoint_path = os.path.abspath(args_cli.checkpoint)
    if not os.path.exists(checkpoint_path):
        raise FileNotFoundError(f"Checkpoint not found at: {checkpoint_path}")
        
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"[INFO] Loading checkpoint from: {checkpoint_path} on {device}")
    
    checkpoint = load_training_checkpoint(checkpoint_path, device)
    config_dict = checkpoint["config"]
    
    # Build policy
    policy_cfg = Solo12DiffusionPolicyConfig(
        history=config_dict["dataset"]["history"],
        action_horizon=config_dict["dataset"]["action_horizon"],
        d_model=config_dict["model"]["d_model"],
        nhead=config_dict["model"]["nhead"],
        num_layers=config_dict["model"]["num_layers"],
        dropout=config_dict["model"]["dropout"],
        num_train_timesteps=config_dict["diffusion"]["num_train_timesteps"],
        beta_start=config_dict["diffusion"]["beta_start"],
        beta_end=config_dict["diffusion"]["beta_end"],
        beta_schedule=config_dict["diffusion"]["beta_schedule"],
        prediction_type=config_dict["diffusion"]["prediction_type"],
        variance_type=config_dict["diffusion"]["variance_type"],
        clip_sample=config_dict["diffusion"]["clip_sample"],
        cfg_dropout_prob=config_dict["diffusion"]["cfg_dropout_prob"],
        num_inference_steps=args_cli.num_inference_steps,
    )

    
    policy = Solo12DiffusionPolicy(policy_cfg)
    policy.load_state_dict(checkpoint["ema_model_state_dict"])
    policy.set_normalizer_stats(checkpoint["normalizer_stats"])
    policy.to(device)
    policy.eval()
    
    history_len = policy_cfg.history
    
    # Override environment settings
    env_cfg.scene.num_envs = args_cli.num_envs
    env_cfg.sim.device = args_cli.device if args_cli.device is not None else env_cfg.sim.device
    env_cfg.episode_length_s = 1.0e9  # Disable automatic resets
    
    if getattr(env_cfg, "events", None):
        env_cfg.events = None
    if hasattr(env_cfg, "enable_observation_corruption"):
        env_cfg.enable_observation_corruption = False
    if hasattr(env_cfg, "actuation_delay_range"):
        env_cfg.actuation_delay_range = (0, 0)
    if hasattr(env_cfg, "base_push_interval_range_s"):
        env_cfg.base_push_interval_range_s = (1.0e9, 1.0e9)

    # Build environment
    env = gym.make(args_cli.task, cfg=env_cfg)
    vec_env = RslRlVecEnvWrapper(env, clip_actions=agent_cfg.clip_actions)
    raw_env = env.unwrapped
    joint_ids = raw_env._joint_ids
    num_envs = args_cli.num_envs
    
    dt = env.step_dt if hasattr(env, "step_dt") else raw_env.step_dt
    print(f"[INFO] Environment built. Running control at {1/dt:.1f}Hz...")

    # Visual camera follow setup
    camera_look_at = np.array([0.0, 0.0, 0.35])
    camera_offset = np.array([-2.0, 0.0, 0.8])
    
    # Initialize rolling history buffers
    obs_buffer = torch.zeros((num_envs, history_len, 42), device=device)
    goal_buffer = torch.zeros((num_envs, history_len, 11), device=device)
    last_action = torch.zeros((num_envs, 12), device=device)

    # Reset environment and obtain starting pose
    obs = vec_env.reset()
    start_pos = raw_env._robot.data.root_pos_w.cpu().numpy()
    time.sleep(0.5)

    # Load or generate planned path
    if args_cli.path_file is not None and os.path.exists(args_cli.path_file):
        print(f"[INFO] Loading planned path from file: {args_cli.path_file}")
        path_array = np.load(args_cli.path_file)
        if path_array.shape[1] == 3:
            # Calculate tangent yaws automatically
            yaws = [0.0]
            for idx in range(1, len(path_array)):
                yaws.append(np.arctan2(path_array[idx, 1] - path_array[idx-1, 1], path_array[idx, 0] - path_array[idx-1, 0]))
            yaws_w = np.array(yaws, dtype=np.float32)
            path_w = path_array.astype(np.float32)
        else:
            path_w = path_array[:, :3].astype(np.float32)
            yaws_w = path_array[:, 3].astype(np.float32)
        print(f"[INFO] Loaded path with {len(path_w)} points.")
    else:
        # Default: generate a straight 3-meter path starting at the robot's initial position
        # and transitioning to crouch height (0.16m) at x = 1.5m
        print(f"[INFO] No path file provided (or not found). Generating default straight 3-meter path.")
        path_points = []
        for dx in np.linspace(0, 3.0, 60):
            x = start_pos[0, 0] + dx
            y = start_pos[0, 1]
            z = 0.24 if dx < 1.5 else 0.16
            path_points.append([x, y, z])
        path_w = np.array(path_points, dtype=np.float32)
        yaws_w = np.zeros(len(path_w), dtype=np.float32)
        
    cumulative_lengths = cumulative_xy_lengths(path_w)

    step_count = 0

    # Helper to compute goal for current step
    def get_current_goal(elapsed_time_s: float) -> torch.Tensor:
        rem_t = max(args_cli.time_budget - elapsed_time_s, dt)
        return compute_path_following_goal(raw_env, path_w, yaws_w, cumulative_lengths, rem_t, args_cli.desired_speed, device)

    # Bootstrap the rolling buffers
    with torch.no_grad():
        initial_obs = get_proprioception_obs(raw_env, joint_ids, last_action)
        initial_goal = get_current_goal(0.0)
        for t_h in range(history_len):
            obs_buffer[:, t_h] = initial_obs
            goal_buffer[:, t_h] = initial_goal

    while simulation_app.is_running():
        elapsed_time = step_count * dt
        with torch.inference_mode():
            # 1. Get current step observation and goal vector
            current_obs = get_proprioception_obs(raw_env, joint_ids, last_action)
            current_goal = get_current_goal(elapsed_time)
            
            # 2. Slide buffers
            obs_buffer = torch.cat([obs_buffer[:, 1:], current_obs.unsqueeze(1)], dim=1)
            goal_buffer = torch.cat([goal_buffer[:, 1:], current_goal.unsqueeze(1)], dim=1)
            
            # 3. Query the Diffusion Policy using Receding Horizon Control (RHC)
            actions_chunk = policy.predict_action_denormalized(
                obs_buffer, 
                goal_buffer, 
                guidance_scale=args_cli.guidance_scale
            )
            action_step = actions_chunk[:, 0] # (num_envs, 12)
            
            # 4. Apply action in simulation
            obs, _, dones, _ = vec_env.step(action_step)
            
            # 5. Update last action for the next timestep
            last_action = action_step.clone()
            
            # 6. Check resets and clear buffers for reset envs
            for i in range(num_envs):
                if dones[i]:
                    print(f"[INFO] Env {i} reset.")
                    last_action[i] = 0.0
                    reset_obs = get_proprioception_obs(raw_env, joint_ids, last_action)
                    reset_goal = get_current_goal(elapsed_time)
                    obs_buffer[i, :] = reset_obs
                    goal_buffer[i, :] = reset_goal

        # Update camera follow
        try:
            root_pos = raw_env._robot.data.root_pos_w[0].cpu().numpy()
            eye_pos = root_pos + camera_offset
            target_look = root_pos + camera_look_at
            raw_env.sim.set_camera_view(eye=eye_pos, target=target_look)
        except Exception:
            pass

        # Print current step status info
        if step_count % 10 == 0:
            robot_pos = raw_env._robot.data.root_pos_w[0].cpu().numpy()
            robot_z = robot_pos[2]
            target_dz = current_goal[0, 8].item()
            v_req_val = current_goal[0, 10].item()
            mode_str = "CROUCHING" if robot_z < 0.20 else "WALKING"
            dist_rem = float(np.linalg.norm(path_w[-1, :2] - robot_pos[:2]))
            rem_t = max(args_cli.time_budget - elapsed_time, 0.0)
            
            print(f"Step {step_count:03d} (t={elapsed_time:.2f}s | rem_t={rem_t:.2f}s) | Mode: {mode_str:^10s} | Z: {robot_z:.3f}m | DistRem: {dist_rem:.2f}m | target_dz: {target_dz:+.3f}m | v_req: {v_req_val:.2f}m/s")

        step_count += 1
        time.sleep(dt)

    print("[INFO] Evaluation finished.")
    vec_env.close()


if __name__ == "__main__":
    main()
    simulation_app.close()

